#!/bin/bash
#@Author Shahriar Shovon
#vers. 1.1 Maurizio Bruccoleri (2021-11-03) - resolved issue related to truncated command field value
#@Github https://github.com/shovon8/sysmon
#
printf "%-10s%-15s%-15s%s\n" "PID" "OWNER" "MEMORY" "COMMAND"

function sysmon_main() {
    RAWIN=$(ps -u agent -o pid,user,%mem,command x | grep -v PID | awk '{printf $1":"$2":"}{for(i=4;i<=NF;++i)printf $i""FS ; print ""}')

    for i in $RAWIN
    do
        PID=$(echo $i | cut -d: -f1)
        OWNER=$(echo $i | cut -d: -f2)
        COMMAND=$(echo $i | cut -d: -f3)
        MEMORY=$(pmap $PID | tail -n 1 | awk '/[0-9]K/{print $2}')
        
        printf "%-10s%-15s%-15s%s\n" "$PID" "$OWNER" "$MEMORY" "$COMMAND"
    done
}

sysmon_main | sort -bnr -k3
